export default {
    ABCD: 'ABCD',
    EFGH: 'EFGH',

    GET_ITEMS: 'GET_ITEMS',
    GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
    GET_ITEMS_EXCEPTION: 'GET_ITEMS_EXCEPTION',
    GET_ITEMS_FAIL: 'GET_ITEMS_FAIL'
}