export default {
    ABCD: 'ABCD',
    EFGH: 'EFGH',

    GET_ITEMS: 'GET_ITEMS',
    GET_ITEMS_SUCCESS: 'GET_ITEMS_SUCCESS',
    GET_ITEMS_EXCEPTION: 'GET_ITEMS_EXCEPTION',
    GET_ITEMS_FAIL: 'GET_ITEMS_FAIL',

    SHOW_RESPONSIVE_HEADER_CATEGORIES_MODAL_HANDLER: 'SHOW_RESPONSIVE_HEADER_CATEGORIES_MODAL_HANDLER',
    CLOSE_RESPONSIVE_HEADER_CATEGORIES_MODAL_HANDLER: 'CLOSE_RESPONSIVE_HEADER_CATEGORIES_MODAL_HANDLER',

    FETCH_PRODUCT_CATEGORIES: 'FETCH_PRODUCT_CATEGORIES',
    FETCH_PRODUCT_CATEGORIES_SUCCESS: "FETCH_PRODUCT_CATEGORIES_SUCCESS",
    FETCH_PRODUCT_CATEGORIES_FAIL: "FETCH_PRODUCT_CATEGORIES_FAIL"

}