export default {
    SHOW_FILTER_MODAL: "SHOW_FILTER_MODAL",
    CLOSE_FILTER_MODAL: "CLOSE_FILTER_MODAL",

    SELECT_SORTING_ITEM: "SELECT_SORTING_ITEM",

    SHOW_SORT_DRAWER: "SHOW_SORT_DRAWER",
    CLOSE_SORT_DRAWER: "CLOSE_SORT_DRAWER"
}