export default {
    DELETE_EVERYTHING: "DELETE_EVERYTHING",

    SHOW_CHANGE_EDIT_ADDRESS_MODAL: "SHOW_CHANGE_EDIT_ADDRESS_MODAL",
    CLOSE_CHANGE_EDIT_ADDRESS_MODAL: "CLOSE_CHANGE_EDIT_ADDRESS_MODAL",

    SHOW_CONFIRM_SELECT_TIME_ADDRESS_MODAL: "SHOW_CONFIRM_SELECT_TIME_ADDRESS_MODAL",
    CLOSE_CONFIRM_SELECT_TIME_ADDRESS_MODAL: "CLOSE_CONFIRM_SELECT_TIME_ADDRESS_MODAL",

    GET_CART_VIA_USER_ID_REQUEST: "GET_CART_VIA_USER_ID_REQUEST",
    GET_CART_VIA_USER_ID_SUCCESS: "GET_CART_VIA_USER_ID_SUCCESS",
    GET_CART_VIA_USER_ID_FAIL: "GET_CART_VIA_USER_ID_FAIL",

    INCREASE_PRODUCT_QUANTITY_IN_CART_REQUEST: "INCREASE_PRODUCT_QUANTITY_IN_CART_REQUEST",
    INCREASE_PRODUCT_QUANTITY_IN_CART_SUCCESS: "INCREASE_PRODUCT_QUANTITY_IN_CART_SUCCESS",
    INCREASE_PRODUCT_QUANTITY_IN_CART_FAIL: "INCREASE_PRODUCT_QUANTITY_IN_CART_FAIL",
}