export default {
    DELETE_EVERYTHING: "DELETE_EVERYTHING",

    SHOW_CHANGE_EDIT_ADDRESS_MODAL: "SHOW_CHANGE_EDIT_ADDRESS_MODAL",
    CLOSE_CHANGE_EDIT_ADDRESS_MODAL: "CLOSE_CHANGE_EDIT_ADDRESS_MODAL"
}