export default {
    LOGOUT: 'LOGOUT',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    LOGIN_REQUEST_OTP_REQUEST: 'LOGIN_REQUEST_OTP_REQUEST',
    LOGIN_REQUEST_OTP_SUCCESS: 'LOGIN_REQUEST_OTP_SUCCESS',
    LOGIN_REQUEST_OTP_FAILURE: 'LOGIN_REQUEST_OTP_FAILURE',
}