export default {
    SELECT_ADDRESS: "SELECT_ADDRESS",

    UPDATE_PROFILE_PERSONAL_INFO_NAMES_REQUEST: "UPDATE_PROFILE_PERSONAL_INFO_NAMES_REQUEST",
    UPDATE_PROFILE_PERSONAL_INFO_NAMES_SUCCESS: "UPDATE_PROFILE_PERSONAL_INFO_NAMES_SUCCESS",
    UPDATE_PROFILE_PERSONAL_INFO_NAMES_FAILURE: "UPDATE_PROFILE_PERSONAL_INFO_NAMES_FAILURE",

    GET_PROFILE_PERSONAL_INFO_REQUEST: "GET_PROFILE_PERSONAL_INFO_REQUEST",
    GET_PROFILE_PERSONAL_INFO_SUCCESS: "GET_PROFILE_PERSONAL_INFO_SUCCESS",
    GET_PROFILE_PERSONAL_INFO_FAILURE: "GET_PROFILE_PERSONAL_INFO_FAILURE"
}