export default {
    SELECT_ADDRESS: "SELECT_ADDRESS",

    GET_PROFILE_PERSONAL_INFO_NAMES_REQUEST: "GET_PROFILE_PERSONAL_INFO_NAMES_REQUEST",
    GET_PROFILE_PERSONAL_INFO_NAMES_SUCCESS: "GET_PROFILE_PERSONAL_INFO_NAMES_SUCCESS",
    GET_PROFILE_PERSONAL_INFO_NAMES_FAILURE: "GET_PROFILE_PERSONAL_INFO_NAMES_FAILURE"
}