export default {
    SHOW_ASK_QUESTION_MODAL: "SHOW_ASK_QUESTION_MODAL",
    CLOSE_ASK_QUESTION_MODAL: "CLOSE_ASK_QUESTION_MODAL",

    SHOW_ANSWER_QUESTION_MODAL: "SHOW_ANSWER_QUESTION_MODAL",
    CLOSE_ANSWER_QUESTION_MODAL: "CLOSE_ANSWER_QUESTION_MODAL",

    SELECT_PRODUCT: "SELECT_PRODUCT"
}