export default {
    SHOW_ASK_QUESTION_MODAL: "SHOW_ASK_QUESTION_MODAL",
    CLOSE_ASK_QUESTION_MODAL: "CLOSE_ASK_QUESTION_MODAL",

    SHOW_ANSWER_QUESTION_MODAL: "SHOW_ANSWER_QUESTION_MODAL",
    CLOSE_ANSWER_QUESTION_MODAL: "CLOSE_ANSWER_QUESTION_MODAL",

    SELECT_PRODUCT: "SELECT_PRODUCT",

    GET_PRODUCT_DETAILS_BY_PRODUCT_ID: "GET_PRODUCT_DETAILS_BY_PRODUCT_ID",
    GET_PRODUCT_DETAILS_BY_PRODUCT_ID_SUCCESS: "GET_PRODUCT_DETAILS_BY_PRODUCT_ID_SUCCESS",
    GET_PRODUCT_DETAILS_BY_PRODUCT_ID_FAIL: "GET_PRODUCT_DETAILS_BY_PRODUCT_ID_FAIL",

    GET_SELECTED_PRODUCT_FEATURES: "GET_SELECTED_PRODUCT_FEATURES",
    GET_SELECTED_PRODUCT_FEATURES_SUCCESS: "GET_SELECTED_PRODUCT_FEATURES_SUCCESS",
    GET_SELECTED_PRODUCT_FEATURES_FAIL: "GET_SELECTED_PRODUCT_FEATURES_FAIL"
}