export default {
    SELECT_ACTIVE_ORDER_TAB: "SELECT_ACTIVE_ORDER_TAB",
    SELECT_ACTIVE_OPINION_TAB: "SELECT_ACTIVE_OPINION_TAB",

    SHOW_SUBMIT_OPINION_MODAL_HANDLER: "SHOW_SUBMIT_OPINION_MODAL_HANDLER",
    CLOSE_SUBMIT_OPINION_MODAL_HANDLER: "CLOSE_SUBMIT_OPINION_MODAL_HANDLER",

    SHOW_EDIT_OPINION_MODAL_HANDLER: "SHOW_EDIT_OPINION_MODAL_HANDLER",
    CLOSE_EDIT_OPINION_MODAL_HANDLER: "CLOSE_EDIT_OPINION_MODAL_HANDLER",

    SHOW_DELETE_OPINION_MODAL_HANDLER: "SHOW_DELETE_OPINION_MODAL_HANDLER",
    CLOSE_DELETE_OPINION_MODAL_HANDLER: "CLOSE_DELETE_OPINION_MODAL_HANDLER"
}